### ISSUE TITLE
Project-specific Configurations

### ISSUE THREAD

**Issue by muppetjones** [MagicStack/MagicPython#156]
* **Editor name and version**: Atom 1.30.0
* **Platform**: OSX High Sierra
* **Color scheme**: Dark (irrelevant)
* **MagicPython version**: 1.0.12
* **A sreenshot**: 
* **5-10 lines of surrounding code**:

```
".python.source":
  editor:
    showInvisibles: false
    softWrap: false
    softWrapAtPreferredLineLength: false
```

First, thanks for the great work on MagicPython--I'm a big fan.

I'm trying to setup project-specific settings, but MagicPython only seems to honor the root `config.cson`. I've used both `project-manager` and `atomic-management`, but neither seems to properly override MagicPython--even if there are no values in the root config file.
