### ISSUE TITLE
Highlighting of SQL inside strings

### ISSUE THREAD

**Issue by elpres** [MagicStack/MagicPython#27]
The stock Python package performs syntax highlighting inside strings containing SQL commands. That's rather useful. Do you have plans to add this too?

**Comment by vpetrovykh** [comment]
Could you specify whether you use Sublime Text or Atom?
The philosophy of MagicPython has been to actually highlight various _Python_ features (i.e. %- and {}-style formatting, regular expressions and docstrings), rather than trying to merge and blend Python with other languages. There are really just too many possibilities there: Python strings can easily be SQL, HTML, XML, JavaScript, not to mention Django or Jinja templates as well as TeX. So usually the best we can do is to try and _not_ highlight highly questionable things (see #28, #23, #12).
There is also a fundamental problem with highlighting other languages inside strings: it's very easy to break the highlighting of an entire source file by an incomplete expression inside a string. Try this in the stock package, I believe it should break the highlighter after the regexp string:
```python
foo = spam(a=1)
bar = r'regexp['
baz = spam(a=1)
```
So far, the above issue seems to have some kind of a generic solution in Sublime Text, but not in Atom.
We have some plans for making user-configurable options for what gets actually highlighted inside the strings. As a configurable option it _might_ be useful to highlight SQL, although at the moment I'm not certain how reliable we could make it, so it wouldn't be a priority for now.

**Comment by DanielOaks** [comment]
In terms of knowing what sort of string it is, one thing I've seen work decently is to only highlight SQL when it's fully uppercased. Just the keywords and phrases, like `CREATE TABLE`, `INSERT INTO` and such, since they tend to not come up much outside of specifically SQL statements.

But however you want to handle it. It would be very nice to have, if it's possible at some point.

**Comment by elpres** [comment]
> Could you specify whether you use Sublime Text or Atom?

Sublime Text, and you are correct about that code fragment breaking the syntax highlighter there. Since both examples we've posted show the same irregularities in Sublime and here, on Github, it's probably safe to assume that they both delegate highlighting to the same 3rd party, maybe Pygments, and there is no special handling for these languages embedded in strings built into Sublime.

And I see that this is a tricky thing to implement, but it also does add a lot to the readability of the code if you do use SQL (or any other language). So it comes with costs and benefits, and it's your call whether the benefits are worth it.

**Comment by vpetrovykh** [comment]
Hmm... I've looked at the default SQL grammar that both Sublime Text and Atom seem to be using. The good news is that this particular grammar would not cause problems from within python strings (or, indeed, any other language strings that are delimited with quotes). So including SQL highlighting as a user-configurable option could be possible. Stay tuned.

**Comment by infininight** [comment]
@elprans Github uses TextMate-style grammars for highlighting, see [github/linguist](https://github.com/github/linguist). For python they use this grammar, MagicPython.

@vpetrovykh One issue with matching SQL inside a string can be begin/end matches matching outside the string boundaries, for example:

```python
'SELECT * FROM "table" -- comment'
```

I'm looking at solving this in TextMate by matching either the string content (for single line strings) or each line first then passing it off to the SQL grammar in a patterns array in the capture. Unfortunately I believe this feature is only available in Atom not Sublime Text. Unsure what form of grammars Visual Studio Code handles.

**Comment by vpetrovykh** [comment]
@infininight I understand that generally falling back onto an external grammar can cause issues with string boundaries. It seems that at the moment the only reliable way to use the same basic grammar across Atom, Sublime Text and Visual Studio Code is to include an SQL grammar that is safe to use inside strings (much like we do with regular expressions). This would have to be optional, though, as detecting SQL may cause annoying false positives for all users.

**Comment by movalex** [comment]
Sublime uses not very sophisticated SQL indicator for triple quote highlighting: 
`\s*(?:SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER|WITH)\b`

Is it possible to implement this in VSCode? Seems like a good feature, and used both in Atom and Sublime.

```
    # Triple-quoted raw string, unicode or not, will detect SQL, otherwise regex
    - match: '([uU]?r)(""")'
      captures:
        1: storage.type.string.python
        2: meta.string.python string.quoted.double.block.python punctuation.definition.string.begin.python
      push:
        - meta_content_scope: meta.string.python string.quoted.double.block.python
        - match: '(?={{sql_indicator}})'
          set:
            - meta_scope: meta.string.python string.quoted.double.block.python
            - match: '"""'
              scope: punctuation.definition.string.end.python
              set: after-expression
            - match: ''
              push: scope:source.sql
              with_prototype:
                - match: '(?=""")'
                  pop: true
                - include: escaped-unicode-char
                - include: constant-placeholder
        - match: '(?=\S)'
          set:
            - meta_scope: meta.string.python string.quoted.double.block.python
            - match: '"""'
              scope: punctuation.definition.string.end.python
              set: after-expression
            - match: ''
              push: scope:source.regexp.python
              with_prototype:
                - match: '(?=""")'
                  pop: true
                - include: escaped-unicode-char
```
